### ISSUE TITLE
Null Reference exception on login

### ISSUE THREAD

**Issue by gdgould** [OiCMudkips/marimba#17]
## Bug
When attempting to log in, a null reference exception is thrown, stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Marimba.Club.FindUser(String strName)
   at Marimba.Club.LoginUser(String strName, String strPassword)
   at Marimba.Forms.Login.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

I don't know if my userID is in the system yet, but if not, throwing an exception is still the wrong way to handle it.

## To Replicate
* Create a new empty text file.
* Rename it blank.mrb.  
* Open it with Marimba.  
* Attempt to log in (My UserID "Greyson").

Yes, the blank.mrb trick may be the actual problem, not the null handling in Marimba.Club.FindUser.  (either way it needs to be fixed)

**Comment by gdgould** [comment]
Sorry, do not know how to tag this as a bug.
